name: Run Bambda Checker on every bambda

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Validate Bambdas
        run: |
          [ $(sha256sum BambdaChecker-1.1.jar | awk '{ print $1 }') = '21805c494ccea16158081855326810e3715034900a1cd18d9e2b9ab7f108de57' ]
          java -jar BambdaChecker-1.1.jar validateonly
